name: flutter_diacare
description: A doctor prescription app with advanced features.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.2.1
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  file_selector: ^1.0.3

  # Material You dynamic color
  dynamic_color: ^1.7.0

  # State management
  provider: ^6.1.2

  # Firebase for authentication, chat, and storage
  firebase_core: ^3.1.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.2.7

  # Step counter
  pedometer: ^4.0.1

  # Video call (Jitsi Meet Wrapper for web support)
  jitsi_meet_wrapper: 0.2.0+1

  # Chat UI
  flutter_chat_ui: ^2.5.2

  # HTTP requests (for AI/REST APIs)
  http: ^1.2.1

  # Health package
  health: ^9.0.0

  # UI and utilities
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^1.0.0
  pdf: ^3.11.0
  printing: ^5.13.0
  flutter_typeahead: ^5.2.0

  # For opening pharmacy links
  url_launcher: ^6.3.0

  # Payments
  razorpay_flutter: ^1.4.0

  # Bluetooth
  flutter_blue_plus: ^1.31.13
  # WiFi IoT
  wifi_iot: ^0.3.19

  # Speech to Text
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2

  # The following are transitive dependencies that can be overridden if needed
  # petitparser: ^7.0.0 (removed to resolve version conflict)
  # xml: ^6.6.0 (removed to resolve version conflict)

dev_dependencies:
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.0
  # leak_tracker: ^11.0.1 (removed to resolve version conflict)
  # leak_tracker_flutter_testing: ^3.0.10 (temporarily removed)
  # leak_tracker_testing: 3.0.1 (temporarily removed)
  # source_gen: ^2.0.0 (removed to resolve version conflict)
  # analyzer: ^7.4.5 (removed to resolve version conflict)
  # dart_style: ^3.1.0 (removed to resolve version conflict)
  # _fe_analyzer_shared: ^82.0.0 (removed to resolve version conflict)

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

dependency_overrides:
